name: CI

on: [push, pull_request]

jobs:

  code_quality:
    name: Code quality
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@dprint
      - uses: taiki-e/install-action@v2
        with:
          tool: typos-cli

      - run:  just check

  msv:
    name: Minimum supported version
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@v4
      with:
        path: .emacs.d

    - uses: purcell/setup-emacs@master
      with:
        version: 29.1

    - name: Check emacs version
      run: emacs --version

    - name: Test the config
      run: |
        emacs --batch
