name: CI

on: [push, pull_request]

jobs:

  code_quality:
    name: Code quality
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install latest just release
        uses: taiki-e/install-action@just

      - name: Install latest dprint release
        uses: taiki-e/install-action@dprint

      - name: Ensure `fmt` has been run
        run:  just fmt-check

  test:
    name: ${{ matrix.job.os }} (${{ matrix.job.emacs_version }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: ubuntu-22.04, emacs_version: snapshot }

    steps:
    - uses: actions/checkout@v3
      with:
        path: .emacs.d

    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.job.emacs_version }}

    - name: Check emacs version
      run: emacs --version

    - name: Test the config
      run: |
        emacs --batch
